# yaml
components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: 4         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: 4

        monitor-task-processor:       # for monitoring
            worker_threads: 1
            thread_name: mon-worker

    default_task_processor: main-task-processor  # Task processor in which components start.

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: 8080            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
            listener-monitor:
                # Listen on localhost:8085 for developer/utility requests
                port: $monitor-server-port
                port#fallback: 8086
                connection:
                    in_buffer_size: 32768
                    requests_queue_size_threshold: 100
                task_processor: monitor-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        http-client:
            fs-task-processor: fs-task-processor
            user-agent: userver testsuite

        dns-client:                     # Asynchronous DNS component
            fs-task-processor: fs-task-processor

        congestion-control:
            load-enabled: true
            fake-mode: false

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        distlock-pg:
            cluster: postgresql-service
            table: distlocks
            lockname: foo
            pg-timeout: 1s
            lock-ttl: 10s
            autostart: true
            testsuite-support: true

        tests-control:
            load-enabled: $testsuite-enabled
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
            testpoint-timeout: 10s
            testpoint-url: mockserver/testpoint
            throttling_enabled: false
        testsuite-support:

        postgresql-service:
            dbconnection: 'postgresql://testsuite@localhost:5433/testsuite_support_service'
            blocking_task_processor: fs-task-processor
