# yaml
components_manager:
    components:
        handler-key-value:
            path: /v1/key-value
            task_processor: main-task-processor
            method: GET,DELETE,POST

        key-value-database:
            dbconnection: 'postgresql://testsuite@localhost:15433/pg_key_value'
            blocking_task_processor: fs-task-processor
            dns_resolver: async

        testsuite-support:

        http-client:
            fs-task-processor: main-task-processor

        tests-control:
            method: POST
            path: /tests/{action}
            skip-unregistered-testpoints: true
            task_processor: main-task-processor
            testpoint-timeout: 10s
            testpoint-url: $mockserver/testpoint
            throttling_enabled: false

        server:
            listener:
                port: 8187
                task_processor: main-task-processor
            listener-monitor:
                port: $monitor-server-port
                port#fallback: 8086
                connection:
                    in_buffer_size: 32768
                    requests_queue_size_threshold: 100
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard

        handler-server-monitor:
            path: /service/monitor
            method: GET
            task_processor: main-task-processor

        # /// [dynamic config]
        # yaml
        dynamic-config:
            defaults:
                POSTGRES_CONNECTION_SETTINGS:
                    key-value-database:
                        max-ttl-sec: 60
                        recent-errors-threshold: 100000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500
                POSTGRES_QUERIES_COMMAND_CONTROL:
                    sample_select_value:
                        network_timeout_ms: 70
                        statement_timeout_ms: 40
                    sample_transaction_insert_key_value:
                        network_timeout_ms: 200
                        statement_timeout_ms: 150
        # /// [dynamic config]

        dns-client:
            fs-task-processor: fs-task-processor

    task_processors:
        main-task-processor:
            worker_threads: 4
        fs-task-processor:
            worker_threads: 4

    default_task_processor: main-task-processor
