# yaml
server-name: test-dynamic-configs 1.0
service-name: test_dynamic_configs
logger-level: info

config-server-url: http://localhost:8083/
server-port: 8185
monitor-server-port: 8186

testsuite-enabled: false

userver-dumps-root: /var/cache/test_dynamic_configs/userver-dumps/
access-log-path: /var/log/test_dynamic_configs/access.log
access-tskv-log-path: /var/log/test_dynamic_configs/access_tskv.log
default-log-path: /var/log/test_dynamic_configs/server.log

config-cache: /var/cache/test_dynamic_configs/config_cache.json
