openapi: 3.0.0
info:
    description: Service sample
    title: Service sample
    version: '1.0'

servers:
  - url: uservice-sample.yandex.net
    description: production
  - url: uservice-sample.tst.yandex.net
    description: testing

paths:
    /v1/test:
        get:
            parameters:
              - in: query
                name: uid
                schema:
                    type: string
            responses:
                200:
                    description: OK

components: {}
