# /// [HTTP caching sample - static config cache]
# yaml
components_manager:
    components:                       # Configuring components that were registered via component_list
        cache-http-translations:
            translations-url: 'mockserver/v1/translations'  # Some other microservice listens on this URL

            update-types: full-and-incremental
            full-update-interval: 1h
            update-interval: 15m
# /// [HTTP caching sample - static config cache]

# /// [HTTP caching sample - static config deps]
        http-client:
            fs-task-processor: fs-task-processor

        dns-client:                     # Asynchronous DNS component
            fs-task-processor: fs-task-processor

        testsuite-support:
        tests-control:
            # Some options from server::handlers::HttpHandlerBase
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        server:
            # ...
# /// [HTTP caching sample - static config deps]
            listener:                 # configuring the main listening socket...
                port: 8089            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        handler-greet-user:
            path: /samples/greet
            method: POST
            task_processor: main-task-processor

    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: 4         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: 4

    default_task_processor: main-task-processor  # Task processor in which components start.
